/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/models/uploads/scene.gltf -T -t -o ./public/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/riot_mech_model/scene.tsx -r ./public 
Files: ./public/models/uploads/scene.gltf [9.44KB] > C:\Users\Константин\Documents\page\JavaScript\React\My\vite-3d-store\public\models\data\20250b4a-bb69-4cce-ae6a-29fe0167c429\riot_mech_model\scene-transformed.glb [2.89MB] (-30547%)
Author: SchrisArt (https://sketchfab.com/SchrisArt)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/riot-mech-model-7b8738c8b0ed4561814856503a4642fb
Title: Riot Mech Model
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    MechModel_BodyUp_0: THREE.Mesh
    MechModel_BodyDown_0: THREE.Mesh
  }
  materials: {
    BodyUp: THREE.MeshStandardMaterial
    BodyDown: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/riot_mech_model/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MechModel_BodyUp_0.geometry} material={materials.BodyUp} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.MechModel_BodyDown_0.geometry} material={materials.BodyDown} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/riot_mech_model/scene-transformed.glb')
