/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/models/uploads/scene.gltf -T -t -o ./public/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/2021__aston_martin_valkyrie/scene.tsx -r ./public 
Files: ./public/models/uploads/scene.gltf [94.76KB] > C:\Users\Константин\Documents\page\JavaScript\React\My\vite-3d-store\public\models\data\20250b4a-bb69-4cce-ae6a-29fe0167c429\2021__aston_martin_valkyrie\scene-transformed.glb [1.15MB] (-1115%)
Author: kevin (ケビン) (https://sketchfab.com/sohyalebret)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2021-aston-martin-valkyrie-0ad5999a62be459c8f883ea0b58cf876
Title: 2021 | Aston Martin Valkyrie
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_5: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_26: THREE.Mesh
    Object_34: THREE.Mesh
    Object_47: THREE.Mesh
  }
  materials: {
    AstonMartin_ValkyrieTrackPack_2020Grille4A_Material: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
    AstonMartin_ValkyrieTrackPack_2020Base_Material: THREE.MeshStandardMaterial
    dash2: THREE.MeshPhysicalMaterial
    PaletteMaterial002: THREE.MeshPhysicalMaterial
    light_on: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    EXT_Disc: THREE.MeshStandardMaterial
    EXT_caliper_AT: THREE.MeshStandardMaterial
    Material__25: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshPhysicalMaterial
    INT_ALPHA: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
    AstonMartin_ValkyrieTrackPack_2020LightA_Material: THREE.MeshStandardMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    rim_center2: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/2021__aston_martin_valkyrie/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.AstonMartin_ValkyrieTrackPack_2020Grille4A_Material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.AstonMartin_ValkyrieTrackPack_2020Base_Material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.dash2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.light_on} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.EXT_Disc} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.EXT_caliper_AT} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Material__25} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.PaletteMaterial004} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.INT_ALPHA} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.PaletteMaterial005} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.AstonMartin_ValkyrieTrackPack_2020LightA_Material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.PaletteMaterial006} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.rim_center2} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/2021__aston_martin_valkyrie/scene-transformed.glb')
