/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/models/uploads/scene.gltf -T -t -o ./public/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/scuderia_ferrari_f1_sf23_2023/scene.tsx -r ./public 
Files: ./public/models/uploads/scene.gltf [26.93KB] > C:\Users\Константин\Documents\page\JavaScript\React\My\vite-3d-store\public\models\data\20250b4a-bb69-4cce-ae6a-29fe0167c429\scuderia_ferrari_f1_sf23_2023\scene-transformed.glb [3.75MB] (-13835%)
Author: Redgrund (https://sketchfab.com/redgrund)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scuderia-ferrari-f1-sf23-2023-ecb0f812bc454331bbe721655b0780ec
Title: Scuderia Ferrari F1 SF23 2023
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
  }
  materials: {
    Body_PBR_Material: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/scuderia_ferrari_f1_sf23_2023/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Body_PBR_Material} />
    </group>
  )
}

useGLTF.preload('/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/scuderia_ferrari_f1_sf23_2023/scene-transformed.glb')
