/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/models/uploads/scene.gltf -T -t -o ./public/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/2021__vision_1789__updated__texture/scene.tsx -r ./public 
Files: ./public/models/uploads/scene.gltf [164.09KB] > C:\Users\Константин\Documents\page\JavaScript\React\My\vite-3d-store\public\models\data\20250b4a-bb69-4cce-ae6a-29fe0167c429\2021__vision_1789__updated__texture\scene-transformed.glb [2.39MB] (-1358%)
Author: kevin (ケビン) (https://sketchfab.com/sohyalebret)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2021-vision-1789-updated-texture-c97d4710824b46069b6812ef2d58cf48
Title: 2021 | Vision 1789 | Updated + Texture
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_33: THREE.Mesh
    Object_36: THREE.Mesh
    Object_41: THREE.Mesh
    Object_44: THREE.Mesh
    Object_60: THREE.Mesh
    Object_65: THREE.Mesh
    Object_68: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
  }
  materials: {
    ['23_-_Default']: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshPhysicalMaterial
    BOUCHON: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    LOGO: THREE.MeshStandardMaterial
    INT_PORTE: THREE.MeshStandardMaterial
    PLAQUE: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshPhysicalMaterial
    PaletteMaterial006: THREE.MeshStandardMaterial
    PaletteMaterial007: THREE.MeshStandardMaterial
    glass_centre_volant: THREE.MeshPhysicalMaterial
    PaletteMaterial008: THREE.MeshPhysicalMaterial
    material: THREE.MeshPhysicalMaterial
    PaletteMaterial009: THREE.MeshPhysicalMaterial
    CARBON_IN: THREE.MeshStandardMaterial
    CARTERA: THREE.MeshStandardMaterial
    DISK: THREE.MeshStandardMaterial
    PHARES: THREE.MeshStandardMaterial
    PEDALIER: THREE.MeshStandardMaterial
    STICKERS: THREE.MeshStandardMaterial
    PaletteMaterial010: THREE.MeshStandardMaterial
    SIEGES: THREE.MeshStandardMaterial
    PaletteMaterial011: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/2021__vision_1789__updated__texture/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['23_-_Default']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.BOUCHON} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial004} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.LOGO} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.INT_PORTE} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.PLAQUE} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial005} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.PaletteMaterial006} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.PaletteMaterial007} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.glass_centre_volant} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.PaletteMaterial008} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.PaletteMaterial009} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.CARBON_IN} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.CARTERA} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.DISK} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.PHARES} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.PEDALIER} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.STICKERS} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.PaletteMaterial010} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.SIEGES} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.PaletteMaterial011} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/data/20250b4a-bb69-4cce-ae6a-29fe0167c429/2021__vision_1789__updated__texture/scene-transformed.glb')
